# Network Runner Configuration
max_tool_loop: 8  # Maximum number of tool calling steps before requesting summary
max_human_loop: 4  # Maximum number of human interaction loops
max_tokens: 2048  # Maximum tokens for model responses
temperature: 0.1  # Temperature for model sampling (0.0 = deterministic)
top_p: 1.0  # Top-p sampling parameter 
stdout: true  # Print logs to stdout
model: "claude-3-5-sonnet-20240620"  # Model to use for agent simulation

# Messages
summary_message: "This is a system message. You have exceeded the maximum number of tool calling steps. Summarize your work thus far and report back to your invoker."
human_role_message: "The human user. This is the task message you sent to your top-level client agent: {task_message}\n\nPlease simulate the human user's response to the client agent's response. You are lazy and refuse to do any work but you are fairly flexible in terms of accepting the client agent's ideas.\n\nIf you deem the task complete, please respond with 'TASK COMPLETE'. It is very important that you respond with 'TASK COMPLETE' if you deem the task complete. If you do not respond with 'TASK COMPLETE', the client agent will continue to work on the task."
