# Sample launch configuration for agents-as-tools

# Models to use in the simulation
models:
  - claude-3-5-sonnet-20240620
  - gpt-4o
  - gpt-4o-mini
  - gemini-2.0-flash

# Network specs to run (these should match filenames in sim/network_specs/)
# Do not include the .json extension, it will be added by run.py if needed
networks:
  - test
  - file_my_taxes
  # Add more network specs as needed

# Maximum total number of concurrent jobs
global_max: 4

# Per-model concurrency limits
# Any model not listed here will use the global_max value
per_model_max:
  claude-3-5-sonnet-20240620: 2
  gpt-4o: 1
  gpt-4o-mini: 5
  gemini-2.0-flash: 2
  # gemini will use the global_max (3) since it's not specified here 