# Network Runner Configuration
max_tool_loop: 8  # Maximum number of tool calling steps before requesting summary
max_human_loop: 4  # Maximum number of human interaction loops
stdout: true  # Print logs to stdout
universal_simulator_model: "gpt-4o"  # Model to use for universal simulator
max_total_rounds: 500

sampling_params:
  model: "gpt-4o"
  temperature: 0.0
  top_p: 1.0
  max_tokens: 2048
  max_retries: 3

# Messages
summary_message: "This is a system message. You have exceeded the maximum number of tool calling steps. Summarize your work thus far and report back to your invoker."
human_role_message: "The human user. This is the task message you sent to your top-level client agent: {task_message}\n\nPlease simulate the human user's response to the client agent's response. You are lazy and refuse to do any work but you are fairly flexible in terms of accepting the client agent's ideas.\n\nIf you deem the task complete, please respond with 'TASK COMPLETE'. It is very important that you respond with 'TASK COMPLETE' if you deem the task complete. If you do not respond with 'TASK COMPLETE', the client agent will continue to work on the task."
default_agent_prompt: "You are a helpful agent in a multi-agent system.\n\nYour role is: {agent.name}.\n\nRole description: {agent.description}."
client_agent_prompt: "\n\nAs the top-level client agent, you are responsible for coordinating the other agents to complete the task. You know the user is lazy and refuses to do any work. You should not need to bother the user with locating information since you have access to everything you need through your sub-agents."